sudo: required
services:
  - docker

language: csharp
dotnet: 2.1.4
mono: none

# Upgrade to latest docker from docker.com
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - curl -L -o powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v6.0.1/powershell-6.0.1-linux-x64.tar.gz
  - mkdir powershell && mv ./powershell.tar.gz ./powershell/powershell.tar.gz && cd ./powershell && tar xfz powershell.tar.gz

script:
 - dotnet restore NuGetLite.Server.sln
 - dotnet build NuGetLite.Server.sln
 - cd test/functional && ../../powershell/pwsh -nol -noni -f ./run_test.ps1 && cd ../../
 - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
 - cd src/NuGetLite.Server
 - docker build -t nugetserverlite:$TRAVIS_TAG -t nugetserverlite:latest .