sudo: required
services:
  - docker

 
language: csharp
dotnet: 2.1.4
mono: none

# Upgrade to latest docker from docker.com
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

stages:
  - test
  - name: build_docker_image
    if: tag is present

 jobs:
  include:
    - stage: test
      dotnet: 2.1.4
      script: dotnet restore NuGetLite.Server.sln
      script: dotnet build NuGetLite.Server.sln
      script: cd test/functional
    - stage: build_docker_image
      dotnet: 2.1.4
      script: cd src/NuGetLite.Server
      script: docker build .