sudo: required
services:
  - docker

language: csharp
dotnet: 2.1.4
mono: none

# Upgrade to latest docker from docker.com
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
 - dotnet restore NuGetLite.Server.sln
 - dotnet build NuGetLite.Server.sln
 - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
 - echo "deploy"